### ISSUE TITLE
Bump class validator to 0.14.1

### ISSUE THREAD

**Issue by smaldd14** [Rishikant181/Rettiwt-Core#116]
See this issue https://github.com/typestack/class-validator/issues/2370

Need to bump to 0.14.1 to fix it

**Comment by smaldd14** [comment]
Don't have permission to create a PR or else I would. Thanks for the help in advance!

**Comment by Rishikant181** [comment]
@smaldd14 Strange, you should be able to open pull requests, but might need approval before merging.
