### ISSUE TITLE
Add reply fetching

### ISSUE THREAD

**Issue by omarcinkonis** [Rishikant181/Rettiwt-Core#87]
Add reply fetching, then add it to rettiwt-api

**Comment by Rishikant181** [comment]
Reply fetching is broken unfortunately. For some reason, it always returns the same data after iterating for some number of times. I was never able to make it work :(

I'll be getting back to it shortly though. I've been busy for the past few days and progress has been slow. Hence the late replies,

As always, thanks for the feedback!

**Comment by Rishikant181** [comment]
I apologize for the late reply, but I've been busy for the past few days, working on my degree minor project :(

Progress has been really slow, and I'll be looking into it in details in about a week. I'll let you know about any updates.
